// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: client/api/v0.2/api.proto

package starlight

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reference string `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
}

func (x *ImageReference) Reset() {
	*x = ImageReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_api_v0_2_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageReference) ProtoMessage() {}

func (x *ImageReference) ProtoReflect() protoreflect.Message {
	mi := &file_client_api_v0_2_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageReference.ProtoReflect.Descriptor instead.
func (*ImageReference) Descriptor() ([]byte, []int) {
	return file_client_api_v0_2_api_proto_rawDescGZIP(), []int{0}
}

func (x *ImageReference) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

type ImagePullResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ImagePullResponse) Reset() {
	*x = ImagePullResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_api_v0_2_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImagePullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePullResponse) ProtoMessage() {}

func (x *ImagePullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_api_v0_2_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePullResponse.ProtoReflect.Descriptor instead.
func (*ImagePullResponse) Descriptor() ([]byte, []int) {
	return file_client_api_v0_2_api_proto_rawDescGZIP(), []int{1}
}

func (x *ImagePullResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_client_api_v0_2_api_proto protoreflect.FileDescriptor

var file_client_api_v0_2_api_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x30, 0x2e,
	0x32, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69,
	0x22, 0x2e, 0x0a, 0x0e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x22, 0x29, 0x0a, 0x11, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x47, 0x0a, 0x09, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x50, 0x49, 0x12, 0x3a, 0x0a, 0x09, 0x50, 0x75, 0x6c, 0x6c,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x43, 0x0a, 0x13, 0x64, 0x65, 0x76, 0x2e, 0x6d, 0x63, 0x32, 0x35,
	0x36, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x42, 0x0e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x41, 0x50, 0x49, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1a, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x63, 0x32, 0x35, 0x36, 0x2f,
	0x73, 0x74, 0x61, 0x72, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_client_api_v0_2_api_proto_rawDescOnce sync.Once
	file_client_api_v0_2_api_proto_rawDescData = file_client_api_v0_2_api_proto_rawDesc
)

func file_client_api_v0_2_api_proto_rawDescGZIP() []byte {
	file_client_api_v0_2_api_proto_rawDescOnce.Do(func() {
		file_client_api_v0_2_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_api_v0_2_api_proto_rawDescData)
	})
	return file_client_api_v0_2_api_proto_rawDescData
}

var file_client_api_v0_2_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_client_api_v0_2_api_proto_goTypes = []interface{}{
	(*ImageReference)(nil),    // 0: api.ImageReference
	(*ImagePullResponse)(nil), // 1: api.ImagePullResponse
}
var file_client_api_v0_2_api_proto_depIdxs = []int32{
	0, // 0: api.ClientAPI.PullImage:input_type -> api.ImageReference
	1, // 1: api.ClientAPI.PullImage:output_type -> api.ImagePullResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_api_v0_2_api_proto_init() }
func file_client_api_v0_2_api_proto_init() {
	if File_client_api_v0_2_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_client_api_v0_2_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_api_v0_2_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImagePullResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_api_v0_2_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_api_v0_2_api_proto_goTypes,
		DependencyIndexes: file_client_api_v0_2_api_proto_depIdxs,
		MessageInfos:      file_client_api_v0_2_api_proto_msgTypes,
	}.Build()
	File_client_api_v0_2_api_proto = out.File
	file_client_api_v0_2_api_proto_rawDesc = nil
	file_client_api_v0_2_api_proto_goTypes = nil
	file_client_api_v0_2_api_proto_depIdxs = nil
}
