name: Debian Package
on:
  # PR testing before merge
  pull_request:
    types: 
    - opened
    - edited
    - synchronize
  # For Testing
  push:
    branches:
      - feature_debian_*
  # For Release
  workflow_run:
    workflows: ["Versioning"]
    types:
      - completed
jobs:
  build:
    name: Starlight Daemon
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build deb package
        env:
          APT_UPLOAD_AUTH: ${{ secrets.APT_UPLOAD_AUTH }}
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install net-tools
          curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
          sh /tmp/get-docker.sh
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker run -d --hostname helper --expose 8080 --name helper -v "$(pwd)"/sandbox:/app/upload:rw harbor.yuri.moe/public/helper:latest
          export UPLOAD_URL=http://`docker inspect helper | grep "IPAddress" | grep -o -E '[0-9.]+' | head -n 1`:8080/
          make docker-buildx-multi-arch
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./sandbox/*.deb