name: Go Testing
on:
  # PR testing before merge
  pull_request:
    types: 
    - opened
    - edited
    - synchronize
  # For Testing
  push:
    branches:
      - feature_debian_*
  # For Release
  workflow_run:
    workflows: ["Versioning"]
    types:
      - completed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Test All
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version-file: './go.mod'    
      - name: Login to Goharbor Container Registry
        # This is needed for one of the test cases to check whether Starlight can integrate with Goharbor
        # Please make sure that the registry is available
        # status is available at: http://status-production.mc256.workers.dev
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GOHARBOR_REGISTRY }}
          username: ${{ secrets.GOHARBOR_USERNAME }}
          password: ${{ secrets.GOHARBOR_PASSWORD }}
          logout: true
      - name: Install Buildessentials
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install build-essential make -y
      - name: Install Docker
        uses: docker/setup-buildx-action@v1
      - name: Test
        run: |
          mkdir -p `pwd`/sandbox/etc/starlight
          docker-compose -f demo/compose/docker-compose-example.yaml up -d
          echo '{"port": 8090,"address": "0.0.0.0","log_level": "info","postgres": "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable","default_registry": "reg.yuri.moe","default_registry_alias": ["reg.yuri.moe"],"cache_timeout": 3600}' > `pwd`/sandbox/etc/starlight/starlight-proxy.json
          ls -al `pwd`
          make test